### ISSUE TITLE
Request Token for SanBox

### ISSUE THREAD

**Issue by sabas1080** [iotaledger/sandbox#13]
Hi

I'm looking for the method to get a token and access the sanbox

Thanks

**Comment by kiahmed** [comment]
same requirement here. did you figure out any faucet out there? Also I wonder why can't we just run with testnet flag enabled ?

**Comment by sabas1080** [comment]
Solution enter Discord IOTA Channel and use Testnet
 https://discordapp.com/channels/397872799483428865/400769484727779328

Thanks
