### ISSUE TITLE
not compile

### ISSUE THREAD

**Issue by kostyaBro** [iotaledger/sandbox#6]
_eliot@eliot-GT70:~/prodjects/PMT/iota/sandbox[Google_cloud]$ go build -o sandbox-server ./cmd/server/_
\# _/home/eliot/prodjects/PMT/iota/sandbox_Google_cloud_/cmd/server
cmd/server/main.go:565: too many arguments in call to psClient.CreateSubscription
	have ("golang.org/x/net/context".Context, string, *"cloud.google.com/go/pubsub".Topic, time.Duration, nil)
	want ("golang.org/x/net/context".Context, string, "cloud.google.com/go/pubsub".SubscriptionConfig)
cmd/server/main.go:587: too many arguments in call to psClient.CreateSubscription
	have ("golang.org/x/net/context".Context, string, *"cloud.google.com/go/pubsub".Topic, time.Duration, nil)
	want ("golang.org/x/net/context".Context, string, "cloud.google.com/go/pubsub".SubscriptionConfig)

**Comment by knarz** [comment]
Did you do a `glide install` beforehand?
